branches:
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
  
build_script:
  - qmake ListeningPractice.pro
  - mingw32-make
  
after_build:
  - windeployqt src/release/ListeningPractice.exe
  - rm src/release/*.o
  - rm src/release/*.cpp
  - rm src/release/*.h

#Note: artifacts path should be from root directory
artifacts:
  - path: src/release
    type: zip
